### ISSUE TITLE
A question about `ansi-term`

### ISSUE THREAD

**Issue by noghartt** [viglioni/lauremacs#2]
Reading the `README`, I ended up having a doubt, on "[Some assumptions](https://github.com/Viglioni/lauremacs#some-assumptions)" sections, wouldn't it be better to check the default user terminal from`SHELL` environment variable? With it, turns unnecessary that it's obligatory to have ZSH installed.

A way to "access" the content from this var is in this example:
```
echo $SHELL
```

**Comment by viglioni** [comment]
It is true!

Someday I'll try to remove all these assumptions, but my initial focus is to make a working version to code in typescript, haskell and org-mode

**Comment by viglioni** [comment]
I'll change it soon, tho

`(getenv "SHELL")` solves the problem easily, thanks!

**Comment by viglioni** [comment]
https://github.com/Viglioni/lauremacs/commit/de5573053b124a053cdf3544c2eb625cfa111a48
✅
